<template>
  <div class="NewsFeed section container">


    <div class="news-item columns is-centered" v-for="(tweet, index) in tweets" :key="index">
      <div class="feed column is-6">

        <div class="social-update">
          <div class="media">
            <div class="media-left">
              <figure class="image is-avatar is-48x48">
                <img :src="tweet.authorAvatar" :alt="tweet.author">
              </figure>
            </div>
            <div class="media-content">
              <p class="twitter-header">
                <strong>{{tweet.author}}</strong>
                <span class="meta light-grey"> <time datetime="2016-1-1">· {{tweet.time}}</time></span>
              </p>
              <p class="">{{tweet.text}}</p>
            </div>
          </div>
        </div>

        <div class="card social-attachment">
          <div class="card-image">
            <figure class="image is-4by3">
              <img :src="tweet.attachment.imageUrl" alt="Placeholder image">
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              <h6 class="title is-6">{{tweet.attachment.title}}</h6>
              <p>
                {{tweet.attachment.text}}
              </p>
              <p class="light-grey">
                {{tweet.attachment.source}}
              </p>
            </div>
          </div>
        </div>

        <div class="response">
          <div class="field response-options">
            <span class="buttons has-addons">
              <button
                class="button is-small"
                name="button"
                v-for="(response, index) in tweet.responses"
                :key="'r' + index"
                @click="changeResponse(tweet, response)"
              >
                {{index + 1}}
              </button>
            </span>
          </div>
          <div class="field">
            <div class="control">
              <textarea class="textarea" placeholder="Send us a message" name="notes">{{responseText(tweet)}}</textarea>
            </div>
          </div>
          <div class="field has-text-right">
            <button class="button is-info is-rounded" name="button">
              <span class="icon">
                <i class="fab fa-twitter"></i>
              </span>
            </button>
          </div>
        </div>

      </div>

    </div>
  </div>
</template>


<script>
import { mapGetters } from 'vuex'
export default {
  name: 'app',
  props: [],
  components: {
  },
  mounted: () => {
    // console.log('this.category', this.$route.params.category)
  },
  data: () => ({
    tweets: [
      {
        author: 'Howard Dean',
        authorAvatar: '/static/img/placeholder.png',
        authorHandle: '@GovHowardDean',
        time: '12h',
        text: 'In March, Portugal Made More Than Enough Renewable Energy to Power The Whole Country',
        attachment: {
          imageUrl: '/static/img/placeholder.png',
          title: 'In March, Portugal Made More Than Enough Renewable Energy to Power The Whole Country',
          text: 'The country produced renewable power equal to 103.6 percent of mainland Portugal\'s electrical demand - a feat unmatched in the last 40 years.',
          source: 'npr.org'
        },
        selectedResponse: null,
        responses: [
          {
            text: '41% of respondents say subsidies are the most important measure for driving investment in renewables',
            link: 'https://gofigu.re/349asj8'
          },
          {
            text: 'The world\'s energy mix continues to turn green, with the addition of almost 165GW of renewable generating capacity in 2016.',
            link: 'https://gofigu.re/349asj8'
          },
          {
            text: 'An estimated 6,392TWh of power was generated by renewables in 2017 and this looks set to grow, with global renewableselectricy generation expected to increase to over 8,000TWh by 2022.',
            link: 'https://gofigu.re/349asj8'
          }
        ]
      },
      {
        author: 'Yusef Unjhawala',
        authorAvatar: '/static/img/placeholder.png',
        authorHandle: '@YusifDFI',
        time: 'Apr 5',
        text: 'If we build your dams, we will buy the electricity it produces. If China builds them, don\'t expect us to buil the electricity it produces. You can sell that to Chine- Modi to tell Nepal\'s PM Oli',
        attachment: {
          imageUrl: '/static/img/placeholder.png',
          title: 'If China builds your damns, India won\t buy energy.',
          text: 'One particular dam project, the $2.5-billion Budhi Gandaki project, on a river by the same name in central-western Nepal, is increasingly becoming...',
          source: 'indiaexpress.com'
        },
        selectedResponse: null,
        responses: [
          {
            text: 'Right now, India\'s total renewable capacity is around 42GW of installed capacity and that accounts for between 6 to 7 percent of the energy currently going into the grid.',
            link: 'https://gofigu.re/349asj8'
          },
          {
            text: 'In India, there are around 18,000 villages that are not electrified and about 3,500 of those cannot be connected to the grid, eiter due to cost or practicality.',
            link: 'https://gofigu.re/349asj8'
          },
          {
            text: 'Policies in India have changed significantly and there are essentially no restrictions and no entry barriers with the opportunity to maintain 100 percent ownership (FDI) in renewables.',
            link: 'https://gofigu.re/349asj8'
          }
        ]
      }
    ]
  }),
  computed: {
    ...mapGetters([
    ])
  },
  methods: {
    responseText: function (tweet) {
      let response = tweet.selectedResponse || tweet.responses[0]
      let responseText = response.text + '\n' + response.link
      return responseText
    },
    changeResponse: function (tweet, response) {
      tweet.selectedResponse = response
    }
  }
}
</script>

<style lang="scss" scoped>
.NewsFeed {
  .feed {
    background: #fff;
    border-radius: 4px;
  }
}
.section.is-light {
  background: #ededed;
}
.news-item  {
  margin-bottom: 30px;
}
.media-content {
  overflow: visible;
  p, strong, span, time {
    font-size: 12px !important;
  }
}
.light-grey {
  color: #bebebe;
}
.twitter-header {
  .meta {
  }
}
.social-attachment {
  margin-top: 20px;
  .card-content {
    padding: 10px;
    h6 {
      font-size: 12px;
      font-weight: bold;
      margin: 0px;
    }
    p {
      font-size: 12px;
      margin: 0px;
    }
  }
}
.response {
  margin-top: 30px;
}
@media (min-width: 669px) {
  .NewsFeed {
    padding-left: 0px;
    padding-right: 0px;
  }
  .news-item .column {
    padding-left: 1.5rem;
    padding-right: 1.5rem;
  }
}
</style>
